import re
from typing import List, Dict

class InsecureDeserializationChecker:
    def __init__(self):
        self.vulnerable_patterns = {
            'pickle.loads': 'Unsafe pickle deserialization',
            'pickle.load': 'Unsafe pickle deserialization',
            'yaml.load': 'Unsafe YAML deserialization',
            'json.loads': 'Potential JSON deserialization vulnerability',
            'marshal.loads': 'Unsafe marshal deserialization',
            'shelve.open': 'Unsafe shelve deserialization',
            'dill.loads': 'Unsafe dill deserialization',
            'dill.load': 'Unsafe dill deserialization',
            'joblib.load': 'Unsafe joblib deserialization',
            'jsonpickle.decode': 'Unsafe jsonpickle deserialization',
            'serpent.loads': 'Unsafe serpent deserialization',
            'pyYAML.load': 'Unsafe YAML deserialization',
            'ruamel.yaml.load': 'Unsafe YAML deserialization',
            'xml.etree.ElementTree.parse': 'Unsafe XML parsing',
            'xml.dom.minidom.parse': 'Unsafe XML parsing',
            'xmlrpc.loads': 'Unsafe XML-RPC deserialization',
            'ast.literal_eval': 'Potentially unsafe literal evaluation',
            'eval': 'Unsafe code evaluation',
            'exec': 'Unsafe code execution',
            'pyyaml.load': 'Unsafe YAML deserialization',
            'cPickle.loads': 'Unsafe pickle deserialization',
            'cPickle.load': 'Unsafe pickle deserialization',
            '_pickle.loads': 'Unsafe pickle deserialization',
            '_pickle.load': 'Unsafe pickle deserialization',
            'msgpack.unpackb': 'Potentially unsafe msgpack deserialization',
            'msgpack.unpack': 'Potentially unsafe msgpack deserialization',
            'msgpack_numpy.unpack': 'Unsafe msgpack-numpy deserialization',
            'marshal.load': 'Unsafe marshal deserialization',
            'shelve.open': 'Unsafe shelve deserialization',
            'numpy.load': 'Potentially unsafe NumPy loading',
            'pandas.read_pickle': 'Unsafe pandas pickle loading',
            'pandas.read_json': 'Potentially unsafe JSON loading',
            'pandas.read_xml': 'Potentially unsafe XML loading',
            'scipy.io.loadmat': 'Potentially unsafe MATLAB file loading',
            'h5py.File': 'Potentially unsafe HDF5 loading',
            'torch.load': 'Unsafe PyTorch model loading',
            'keras.models.load_model': 'Potentially unsafe Keras model loading',
            'tensorflow.saved_model.load': 'Potentially unsafe TensorFlow model loading',
            'cloudpickle.loads': 'Unsafe cloudpickle deserialization',
            'cloudpickle.load': 'Unsafe cloudpickle deserialization',
            'copyreg.loads': 'Unsafe copyreg deserialization',
            'copyreg.load': 'Unsafe copyreg deserialization',
            'multiprocessing.reduction.ForkingPickler.loads': 'Unsafe multiprocessing pickle deserialization',
            'multiprocessing.reduction.ForkingPickler.load': 'Unsafe multiprocessing pickle deserialization',
            'jsonschema.validate': 'Potentially unsafe JSON schema validation',
            'configparser.ConfigParser': 'Potentially unsafe config parsing',
            'lxml.etree.parse': 'Unsafe XML parsing',
            'lxml.objectify.parse': 'Unsafe XML parsing',
            'defusedxml.ElementTree.parse': 'Potentially unsafe XML parsing',
            'defusedxml.minidom.parse': 'Potentially unsafe XML parsing',
            'untangle.parse': 'Unsafe XML parsing',
            'xmltodict.parse': 'Potentially unsafe XML parsing',
            'beautifulsoup4.BeautifulSoup': 'Potentially unsafe HTML/XML parsing',
            'bs4.BeautifulSoup': 'Potentially unsafe HTML/XML parsing',
            'html.parser.HTMLParser': 'Potentially unsafe HTML parsing',
            'html5lib.parse': 'Potentially unsafe HTML parsing',
            'json5.loads': 'Potentially unsafe JSON5 deserialization',
            'ujson.loads': 'Potentially unsafe ultra-fast JSON deserialization',
            'rapidjson.loads': 'Potentially unsafe rapid JSON deserialization',
            'simplejson.loads': 'Potentially unsafe JSON deserialization',
            'tomli.loads': 'Potentially unsafe TOML deserialization',
            'tomllib.loads': 'Potentially unsafe TOML deserialization',
            'configobj.ConfigObj': 'Potentially unsafe config parsing',
            'ini.parse': 'Potentially unsafe INI parsing',
            'pythonjsonlogger.jsonlogger.JsonFormatter': 'Potentially unsafe JSON log parsing',
            'plistlib.loads': 'Potentially unsafe property list deserialization',
            'plistlib.load': 'Potentially unsafe property list deserialization',
            'bplist.load': 'Potentially unsafe binary property list deserialization',
            'construct.parse': 'Potentially unsafe binary parsing',
            'biplist.readPlist': 'Potentially unsafe binary property list parsing',
            'parsimonious.Grammar': 'Potentially unsafe grammar parsing',
            'feedparser.parse': 'Potentially unsafe RSS/Atom feed parsing',
            'python_jwt.decode': 'Potentially unsafe JWT decoding',
            'jwt.decode': 'Potentially unsafe JWT decoding',
            'pyjwt.decode': 'Potentially unsafe JWT decoding',
            'itsdangerous.loads': 'Potentially unsafe signed data deserialization',
            'itsdangerous.load_payload': 'Potentially unsafe signed data deserialization',
            'base64.b64decode': 'Potentially unsafe base64 decoding',
            'base64.urlsafe_b64decode': 'Potentially unsafe base64 decoding',
            'urllib.parse.unquote': 'Potentially unsafe URL decoding',
            'urllib.parse.parse_qs': 'Potentially unsafe query string parsing',
            'cgi.parse_qs': 'Potentially unsafe query string parsing',
            'cgi.FieldStorage': 'Potentially unsafe form data parsing',
            'docutils.core.publish_string': 'Potentially unsafe markup processing',
            'docutils.core.publish_file': 'Potentially unsafe markup processing',
            'markdown.markdown': 'Potentially unsafe markdown processing',
            'markdown2.markdown': 'Potentially unsafe markdown processing',
            'mistune.markdown': 'Potentially unsafe markdown processing',
            'commonmark.Parser': 'Potentially unsafe markdown processing',
            'jinja2.Template': 'Potentially unsafe template processing',
            'mako.template.Template': 'Potentially unsafe template processing',
            'chameleon.PageTemplate': 'Potentially unsafe template processing',
            'string.Template': 'Potentially unsafe template processing',
            'email.message_from_string': 'Potentially unsafe email parsing',
            'email.message_from_bytes': 'Potentially unsafe email parsing',
            'email.message_from_file': 'Potentially unsafe email parsing',
            'rfc822.Message': 'Potentially unsafe email parsing',
            'sqlite3.connect': 'Potentially unsafe SQLite operations',
            'mysql.connector.connect': 'Potentially unsafe MySQL operations',
            'psycopg2.connect': 'Potentially unsafe PostgreSQL operations',
            'pymongo.MongoClient': 'Potentially unsafe MongoDB operations',
            'redis.Redis': 'Potentially unsafe Redis operations',
            'cassandra.cluster.Cluster': 'Potentially unsafe Cassandra operations',
            'neo4j.GraphDatabase.driver': 'Potentially unsafe Neo4j operations',
            'elasticsearch.Elasticsearch': 'Potentially unsafe Elasticsearch operations',
            'paramiko.SSHClient': 'Potentially unsafe SSH operations',
            'ftplib.FTP': 'Potentially unsafe FTP operations',
            'telnetlib.Telnet': 'Potentially unsafe Telnet operations',
            'smtplib.SMTP': 'Potentially unsafe SMTP operations',
            'poplib.POP3': 'Potentially unsafe POP3 operations',
            'imaplib.IMAP4': 'Potentially unsafe IMAP operations'
        }

        self.remediation_tips = {
            'pickle.loads': 'Use alternative serialization methods like JSON. If pickle must be used, validate input source and use safeguards like hmac.',
            'pickle.load': 'Use alternative serialization methods like JSON. If pickle must be used, validate input source and use safeguards like hmac.',
            'yaml.load': 'Use yaml.safe_load() instead of yaml.load()',
            'json.loads': 'Validate JSON schema before deserialization. Consider using json.loads() with object_hook parameter for custom deserialization.',
            'marshal.loads': 'Avoid using marshal for untrusted data. Use JSON or other safer alternatives.',
            'shelve.open': 'Validate input data and source. Consider using safer alternatives for untrusted data.',
            'dill.loads': 'Use alternative serialization methods like JSON. Avoid dill for untrusted data.',
            'dill.load': 'Use alternative serialization methods like JSON. Avoid dill for untrusted data.',
            'joblib.load': 'Validate input source and use secure serialization alternatives.',
            'jsonpickle.decode': 'Validate input and consider using plain JSON instead.',
            'serpent.loads': 'Use safer serialization methods like JSON.',
            'pyYAML.load': 'Use pyYAML.safe_load() instead.',
            'ruamel.yaml.load': 'Use ruamel.yaml.safe_load() instead.',
            'xml.etree.ElementTree.parse': 'Use defusedxml library and disable external entity parsing.',
            'xml.dom.minidom.parse': 'Use defusedxml library and disable external entity parsing.',
            'xmlrpc.loads': 'Validate input and disable dangerous features.',
            'ast.literal_eval': 'Ensure input only contains literals.',
            'eval': 'Never use eval() on untrusted input. Use safer alternatives.',
            'exec': 'Never use exec() on untrusted input. Use safer alternatives.',
            'pyyaml.load': 'Use pyyaml.safe_load() instead.',
            'cPickle.loads': 'Use JSON or other safe serialization methods.',
            'cPickle.load': 'Use JSON or other safe serialization methods.',
            '_pickle.loads': 'Use JSON or other safe serialization methods.',
            '_pickle.load': 'Use JSON or other safe serialization methods.',
            'msgpack.unpackb': 'Validate input before deserialization.',
            'msgpack.unpack': 'Validate input before deserialization.',
            'msgpack_numpy.unpack': 'Use safer alternatives for untrusted data.',
            'marshal.load': 'Use JSON or other safer serialization methods.',
            'numpy.load': 'Use allow_pickle=False and validate input source.',
            'pandas.read_pickle': 'Use pandas.read_json() or other safer methods.',
            'pandas.read_json': 'Validate JSON schema before loading.',
            'pandas.read_xml': 'Use defusedxml and validate input.',
            'scipy.io.loadmat': 'Validate input source and format.',
            'h5py.File': 'Validate input source and format.',
            'torch.load': 'Use safe_load() or validate source thoroughly.',
            'keras.models.load_model': 'Validate model source and format.',
            'tensorflow.saved_model.load': 'Validate model source and format.',
            'cloudpickle.loads': 'Use safer serialization alternatives.',
            'cloudpickle.load': 'Use safer serialization alternatives.',
            'copyreg.loads': 'Use JSON or other safe alternatives.',
            'copyreg.load': 'Use JSON or other safe alternatives.',
            'multiprocessing.reduction.ForkingPickler.loads': 'Use safe IPC methods.',
            'multiprocessing.reduction.ForkingPickler.load': 'Use safe IPC methods.',
            'jsonschema.validate': 'Use strict schema validation.',
            'configparser.ConfigParser': 'Validate config source and format.',
            'lxml.etree.parse': 'Use defusedxml and disable dangerous features.',
            'lxml.objectify.parse': 'Use defusedxml and disable dangerous features.',
            'defusedxml.ElementTree.parse': 'Enable all safety features.',
            'defusedxml.minidom.parse': 'Enable all safety features.',
            'untangle.parse': 'Use defusedxml instead.',
            'xmltodict.parse': 'Disable external entities and validate input.',
            'beautifulsoup4.BeautifulSoup': 'Use safe parser like "lxml" or "html.parser".',
            'bs4.BeautifulSoup': 'Use safe parser like "lxml" or "html.parser".',
            'html.parser.HTMLParser': 'Validate input and handle malformed HTML.',
            'html5lib.parse': 'Validate input and handle malformed HTML.',
            'json5.loads': 'Validate input before parsing.',
            'ujson.loads': 'Validate input before parsing.',
            'rapidjson.loads': 'Use schema validation.',
            'simplejson.loads': 'Validate input with schema.',
            'tomli.loads': 'Validate TOML input.',
            'tomllib.loads': 'Validate TOML input.',
            'configobj.ConfigObj': 'Validate config source.',
            'ini.parse': 'Validate INI file source.',
            'pythonjsonlogger.jsonlogger.JsonFormatter': 'Validate log format.',
            'plistlib.loads': 'Validate property list input.',
            'plistlib.load': 'Validate property list input.',
            'bplist.load': 'Validate binary plist source.',
            'construct.parse': 'Validate binary format.',
            'biplist.readPlist': 'Validate plist source.',
            'parsimonious.Grammar': 'Validate grammar rules.',
            'feedparser.parse': 'Sanitize feed input.',
            'python_jwt.decode': 'Verify signature and validate claims.',
            'jwt.decode': 'Verify signature and validate claims.',
            'pyjwt.decode': 'Verify signature and validate claims.',
            'itsdangerous.loads': 'Use proper secret key and validate input.',
            'itsdangerous.load_payload': 'Use proper secret key and validate input.',
            'base64.b64decode': 'Validate input format.',
            'base64.urlsafe_b64decode': 'Validate input format.',
            'urllib.parse.unquote': 'Validate URL encoding.',
            'urllib.parse.parse_qs': 'Validate query string.',
            'cgi.parse_qs': 'Validate form input.',
            'cgi.FieldStorage': 'Validate form input.',
            'docutils.core.publish_string': 'Disable raw and file directives.',
            'docutils.core.publish_file': 'Disable raw and file directives.',
            'markdown.markdown': 'Disable unsafe extensions.',
            'markdown2.markdown': 'Disable unsafe extensions.',
            'mistune.markdown': 'Use safe mode.',
            'commonmark.Parser': 'Validate markdown input.',
            'jinja2.Template': 'Use autoescape and sandbox mode.',
            'mako.template.Template': 'Use strict  and escape filters.',
            'chameleon.PageTemplate': 'Use strict mode and escape.',
            'string.Template': 'Validate template variables.',
            'email.message_from_string': 'Validate email format.',
            'email.message_from_bytes': 'Validate email format.',
            'email.message_from_file': 'Validate email format.',
            'rfc822.Message': 'Use email.parser instead.',
            'sqlite3.connect': 'Use parameterized queries.',
            'mysql.connector.connect': 'Use prepared statements.',
            'psycopg2.connect': 'Use prepared statements.',
            'pymongo.MongoClient': 'Validate queries and use secure connection.',
            'redis.Redis': 'Use SSL and authentication.',
            'cassandra.cluster.Cluster': 'Use SSL and authentication.',
            'neo4j.GraphDatabase.driver': 'Use SSL and authentication.',
            'elasticsearch.Elasticsearch': 'Use SSL and API keys.',
            'paramiko.SSHClient': 'Validate host keys.',
            'ftplib.FTP': 'Use FTPS instead.',
            'telnetlib.Telnet': 'Use SSH instead.',
            'smtplib.SMTP': 'Use STARTTLS or SMTP_SSL.',
            'poplib.POP3': 'Use POP3_SSL.',
            'imaplib.IMAP4': 'Use IMAP4_SSL.'
        }

        self.found_vulnerabilities: List[Dict] = []

    def analyze_file(self, file_path: str) -> List[Dict]:
        try:
            with open(file_path, 'r') as f:
                content = f.read()

            for line_no, line in enumerate(content.splitlines(), start=1):
                for vuln_type, pattern in self.vulnerable_patterns.items():
                    if re.search(pattern, line):
                        self.found_vulnerabilities.append({
                            "type": vuln_type,
                            "line": line_no,
                            "content": line.strip(),
                            "remediation": self.remediation_tips[vuln_type]
                        })

            return self.found_vulnerabilities
        
        except Exception as e:
            print(f"Error while running InsecureDeserializationChecker: {e}")
            return []  # Return an empty list on error

    def display_results(self) -> None:
        if not self.found_vulnerabilities:
            print("No insecure deserialization vulnerabilities found.")
            return

        print("\n=== Insecure Deserialization Detection Results ===\n")
        for vuln in sorted(self.found_vulnerabilities, key=lambda x: x["line"]):
            print(f"Type: {vuln['type']}")
            print(f"Line {vuln['line']}: {vuln['content']}")
            print(f"Remediation: {vuln['remediation']}")
            print("-" * 50 + "\n")