# -*- coding: utf-8 -*-
"""Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F0yJw8AqdN7KbexBNIHVNDGGaGJB3WQX
"""

# Python Analyzer (your existing code)
import ast
import os
from collections import defaultdict
import math

class PythonComplexityAnalyzer(ast.NodeVisitor):
    def __init__(self):
        self.current_function = None
        self.function_complexity = {}
        self.function_details = defaultdict(list)
        self.nested_level = 0
        self.loop_stack = []
        self.space_complexity = defaultdict(lambda: "O(1)")

    def visit_FunctionDef(self, node):
        self.current_function = node.name
        self.function_complexity[self.current_function] = ("O(1)", [])
        self.space_complexity[self.current_function] = "O(1)"
        self.nested_level = 0
        self.loop_stack = []
        self.generic_visit(node)
        self.current_function = None

    def visit_For(self, node):
        if self.current_function:
            self.nested_level += 1
            loop_info = {
                'type': 'for',
                'variable': getattr(node.target, 'id', '?'),
                'iter': ast.unparse(node.iter),
                'line': node.lineno,
                'nested_level': self.nested_level
            }
            self.loop_stack.append(loop_info)
            self._update_function_complexity("n", loop_info)
            self.generic_visit(node)
            self.nested_level -= 1
            self.loop_stack.pop()

    def visit_While(self, node):
        if self.current_function:
            self.nested_level += 1
            loop_info = {
                'type': 'while',
                'condition': ast.unparse(node.test),
                'line': node.lineno,
                'nested_level': self.nested_level
            }
            self.loop_stack.append(loop_info)
            self._update_function_complexity("n", loop_info, condition=ast.unparse(node.test))
            self.generic_visit(node)
            self.nested_level -= 1
            self.loop_stack.pop()

    def visit_Call(self, node):
        if self.current_function:
            func_name = None
            if isinstance(node.func, ast.Name):
                func_name = node.func.id
            elif isinstance(node.func, ast.Attribute):
                func_name = node.func.attr

            call_complexity_val = "1"
            suggestion = None

            if func_name in ['sort', 'sorted']:
                call_complexity_val = 'n log n'
                suggestion = "Consider if sorting is necessary..."
            elif func_name in ['sum', 'min', 'max', 'len', 'any', 'all']:
                call_complexity_val = 'n'
                suggestion = "Generally linear in input size."
            elif func_name in ['append', 'extend', 'insert']:
                call_complexity_val = '1'
            elif func_name in ['get', '__getitem__']:
                call_complexity_val = '1'
            elif func_name in ['keys', 'values', 'items']:
                call_complexity_val = 'n'
            elif func_name in ['add', 'remove', '__contains__']:
                call_complexity_val = '1'
            elif func_name in ['combinations', 'permutations', 'product']:
                call_complexity_val = 'n^r'
                suggestion = "Combinatorial functions can be expensive."
            elif func_name in ['math.pow', 'math.log', 'math.exp', 'math.sqrt']:
                call_complexity_val = '1'
            elif func_name in ['bisect_left', 'bisect_right', 'heapq.heappush', 'heapq.heappop']:
                call_complexity_val = 'log n'

            call_info = {
                'type': 'call',
                'func': func_name,
                'line': node.lineno,
                'complexity': call_complexity_val,
                'suggestion': suggestion
            }
            self._update_function_complexity(call_complexity_val, call_info)
        self.generic_visit(node)

    def _update_function_complexity(self, new_complexity, component_info, condition=None):
        if self.current_function:
            current_complexity_str, components = self.function_complexity[self.current_function]
            if current_complexity_str == "O(1)":
                self.function_complexity[self.current_function] = (f"O({new_complexity})", components + [component_info])
            elif current_complexity_str == f"O({new_complexity})":
                self.function_complexity[self.current_function] = (current_complexity_str, components + [component_info])
            elif current_complexity_str.startswith("O(n") and new_complexity == "n":
                power = 1
                if '^' in current_complexity_str:
                    try:
                        power = int(current_complexity_str.split('^')[1][:-1])
                    except ValueError:
                        pass
                self.function_complexity[self.current_function] = (f"O(n^{power + 1})", components + [component_info])
            elif current_complexity_str.startswith("O(n") and new_complexity == "log n":
                self.function_complexity[self.current_function] = (f"{current_complexity_str.split(')')[0]} log n)", components + [component_info])
            elif current_complexity_str == "O(log n)" and new_complexity == "n":
                self.function_complexity[self.current_function] = ("O(n log n)", components + [component_info])
            elif new_complexity == "n" and current_complexity_str == "O(1)":
                self.function_complexity[self.current_function] = ("O(n)", components + [component_info])
            elif new_complexity == "log n" and current_complexity_str == "O(1)":
                self.function_complexity[self.current_function] = ("O(log n)", components + [component_info])
            elif new_complexity == "n log n" and current_complexity_str == "O(n)":
                self.function_complexity[self.current_function] = ("O(n log n)", components + [component_info])
            elif new_complexity == "n log n" and current_complexity_str == "O(log n)":
                self.function_complexity[self.current_function] = ("O(n log n)", components + [component_info])
            elif new_complexity == "n log n" and current_complexity_str == "O(1)":
                self.function_complexity[self.current_function] = ("O(n log n)", components + [component_info])
            elif new_complexity != "1" and current_complexity_str == "O(1)":
                self.function_complexity[self.current_function] = (f"O({new_complexity})", components + [component_info])

    def visit_ListComp(self, node):
        if self.current_function:
            self.space_complexity[self.current_function] = self._update_space_complexity(self.space_complexity[self.current_function], "n")
        self.generic_visit(node)

    def visit_DictComp(self, node):
        if self.current_function:
            self.space_complexity[self.current_function] = self._update_space_complexity(self.space_complexity[self.current_function], "n")
        self.generic_visit(node)

    def visit_SetComp(self, node):
        if self.current_function:
            self.space_complexity[self.current_function] = self._update_space_complexity(self.space_complexity[self.current_function], "n")
        self.generic_visit(node)

    def visit_GeneratorExp(self, node):
        self.generic_visit(node)

    def visit_Name(self, node):
        if self.current_function and isinstance(node.ctx, ast.Store):
            self.space_complexity[self.current_function] = self._update_space_complexity(self.space_complexity[self.current_function], "1")
        self.generic_visit(node)

    def visit_List(self, node):
        if self.current_function:
            self.space_complexity[self.current_function] = self._update_space_complexity(self.space_complexity[self.current_function], "n")
        self.generic_visit(node)

    def visit_Dict(self, node):
        if self.current_function:
            self.space_complexity[self.current_function] = self._update_space_complexity(self.space_complexity[self.current_function], "n")
        self.generic_visit(node)

    def visit_Set(self, node):
        if self.current_function:
            self.space_complexity[self.current_function] = self._update_space_complexity(self.space_complexity[self.current_function], "n")
        self.generic_visit(node)

    def _update_space_complexity(self, current_complexity, new_term):
        if current_complexity == "O(1)":
            return f"O({new_term})"
        elif new_term == "1":
            return current_complexity
        elif current_complexity == f"O({new_term})":
            return current_complexity
        elif current_complexity.startswith("O(n") or new_term == "n":
            return "O(n)"
        elif current_complexity.startswith("O(log n)") and new_term == "n":
            return "O(n)"
        elif current_complexity == "O(n)" and new_term == "log n":
            return "O(n)"
        elif current_complexity.startswith("O(n)") and new_term.startswith("log n"):
            return "O(n log n)"
        elif current_complexity.startswith("O(log n)") and new_term.startswith("O(log n)"):
            return "O(log n)"
        else:
            return f"O({current_complexity.split('(')[1][:-1]} + {new_term})"

def analyze_python_code(filename):
    try:
        with open(filename, 'r') as f:
            code = f.read()
    except FileNotFoundError:
        return f"Error: File '{filename}' not found."

    tree = ast.parse(code)
    base, ext = os.path.splitext(filename)
    ast_filename = f"ast_tree_{base}{ext}.txt"

    with open(ast_filename, "w") as f:
        f.write(ast.dump(tree, indent=4))
    print(f"Abstract Syntax Tree (AST) saved to '{ast_filename}'")

    defined_names = set()
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.ClassDef)):
            defined_names.add(node.name)
        elif isinstance(node, ast.Name) and isinstance(node.ctx, ast.Store):
            defined_names.add(node.id)

    used_names = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Name) and isinstance(node.ctx, ast.Load):
            used_names.add(node.id)
        elif isinstance(node, (ast.Call, ast.Attribute)):
            if hasattr(node, 'func'):
                if isinstance(node.func, ast.Name):
                    used_names.add(node.func.id)
                elif isinstance(node.func, ast.Attribute) and isinstance(node.func.value, ast.Name):
                    used_names.add(node.func.value.id)

    unused = defined_names - used_names
    unused_vars_funcs = {name for name in unused if name not in [mod.module.split('.')[0] for mod in tree.body if isinstance(mod, ast.ImportFrom)]}
    imported_names = set()
    for node in tree.body:
        if isinstance(node, ast.Import):
            for alias in node.names:
                imported_names.add(alias.name.split('.')[0])
        elif isinstance(node, ast.ImportFrom):
            imported_names.add(node.module.split('.')[0])

    used_imports = set()
    for name in used_names:
        if name in imported_names:
            used_imports.add(name)

    unused_imports = imported_names - used_imports

    complexity_analyzer = PythonComplexityAnalyzer()
    complexity_analyzer.visit(tree)

    complexity_report = {}
    for func, (complexity_str, components) in complexity_analyzer.function_complexity.items():
        details = []
        for comp in components:
            if comp['type'] in ('for', 'while'):
                details.append({
                    'type': 'loop',
                    'location': f"{comp['type']} loop at line {comp['line']}",
                    'detail': f"iterates over {comp.get('iter', '?')}",
                    'complexity': 'O(n)' if comp['nested_level'] == 1 else f"O(n^{comp['nested_level']})",
                    'suggestion': "Nested loops can lead to polynomial complexity - consider alternatives" if comp['nested_level'] > 1 else None
                })
            elif comp['type'] == 'call':
                details.append({
                    'type': 'call',
                    'location': f"call to {comp['func']}() at line {comp['line']}",
                    'complexity': f"O({comp['complexity']})",
                    'suggestion': comp['suggestion']
                })

        complexity_report[func] = {
            'time_complexity': complexity_str,
            'space_complexity': complexity_analyzer.space_complexity.get(func, "O(1)"),
            'components': details
        }

    return {
        "unused_imports": list(unused_imports),
        "unused_variables_functions": list(unused_vars_funcs),
        "complexity": complexity_report,
        "original_code": code
    }

def remove_unused_python_code(code, unused_imports, unused_variables_functions):
    tree = ast.parse(code)
    new_body = []
    defined_in_scope = set()

    for node in tree.body:
        keep_node = True
        if isinstance(node, ast.Import):
            node.names = [alias for alias in node.names if alias.name.split('.')[0] not in unused_imports]
            if not node.names:
                keep_node = False
        elif isinstance(node, ast.ImportFrom):
            if node.module and node.module.split('.')[0] in unused_imports:
                keep_node = False
        elif isinstance(node, (ast.FunctionDef, ast.ClassDef, ast.Assign)):
            node_names = []
            if isinstance(node, (ast.FunctionDef, ast.ClassDef)):
                node_names.append(node.name)
            elif isinstance(node, ast.Assign):
                for target in node.targets:
                    if isinstance(target, ast.Name):
                        node_names.append(target.id)

            for name in node_names:
                if name in unused_variables_functions:
                    keep_node = False
                    break

        if keep_node:
            new_body.append(node)
            if isinstance(node, (ast.FunctionDef, ast.ClassDef)):
                defined_in_scope.add(node.name)
            elif isinstance(node, ast.Assign):
                for target in node.targets:
                    if isinstance(target, ast.Name):
                        defined_in_scope.add(target.id)

    new_tree = ast.Module(body=new_body, type_ignores=[])
    ast.fix_missing_locations(new_tree)
    optimized_code = ast.unparse(new_tree)
    return optimized_code

def suggest_python_secure_coding(code):
    suggestions = []
    tree = ast.parse(code)

    for node in ast.walk(tree):
        if isinstance(node, ast.Call) and isinstance(node.func, ast.Name) and node.func.id == 'input':
            suggestions.append({
                "type": "security",
                "location": f"Input function used at line {node.lineno}",
                "suggestion": "Sanitize and validate user input to prevent injection vulnerabilities."
            })
        elif isinstance(node, ast.Call) and (
            (isinstance(node.func, ast.Name) and node.func.id in ['eval', 'exec']) or
            (isinstance(node.func, ast.Attribute) and node.func.attr in ['eval', 'exec'])
        ):
            suggestions.append({
                "type": "security",
                "location": f"Potentially unsafe function call (`{ast.unparse(node.func)}`) at line {node.lineno}",
                "suggestion": "Avoid using `eval()` and `exec()` as they can execute arbitrary code."
            })
        elif isinstance(node, ast.Call) and isinstance(node.func, ast.Name) and node.func.id == 'open':
            if len(node.args) > 0 and isinstance(node.args[0], ast.Constant) and isinstance(node.args[0].value, str):
                if node.args[0].value.startswith('/'):
                    suggestions.append({
                        "type": "security",
                        "location": f"File operation with absolute path at line {node.lineno}",
                        "suggestion": "Consider using relative paths or managing paths more carefully."
                    })
        elif isinstance(node, ast.Import) or isinstance(node, ast.ImportFrom):
            for alias in node.names:
                if alias.name in ['pickle', 'marshal', 'shelve']:
                    suggestions.append({
                        "type": "security",
                        "location": f"Import of potentially unsafe module `{alias.name}` at line {node.lineno}",
                        "suggestion": "Be cautious when loading data from untrusted sources."
                    })

    return suggestions

import re
import os
from collections import defaultdict, deque

class CppAnalyzer:
    CONTROL_KEYWORDS = {
        'if', 'for', 'while', 'switch', 'do', 'else', 'case', 'catch',
        'return', 'sizeof', 'delete', 'throw', 'break', 'continue', 'goto'
    }

    def __init__(self):
        self.function_defs = {}           # func_name -> (start_line, end_line, code)
        self.function_calls = defaultdict(set)  # func_name -> set(called_func_names)
        self.includes = {}                # include_file -> line_number
        self.used_includes = set()
        self.structure_tree = []
        self.function_complexity = {}
        self.optimized_code_saved = False  # Flag to track if optimized code is saved

    def analyze_file(self, filename):
        try:
            with open(filename, 'r') as f:
                code = f.read()
        except FileNotFoundError:
            print(f"Error: File '{filename}' not found.")
            return

        cleaned_code = self._remove_comments_and_strings(code)
        lines = code.split('\n')

        # 1. Analyze includes
        self._analyze_includes(code)

        # 2. Analyze function definitions and calls
        self._analyze_functions_and_calls(cleaned_code, lines)

        # 3. Build call graph and find used functions starting from main()
        used_functions = self._find_used_functions()

        # 4. Find unused functions/includes
        unused_functions = set(self.function_defs) - used_functions
        unused_includes = set(self.includes) - self.used_includes

        # 5. Print unused items
        print("UNUSED INCLUDES:")
        for inc in unused_includes:
            print(f"  {inc} (line {self.includes[inc]})")
        print("\nUNUSED FUNCTIONS:")
        for func in unused_functions:
            print(f"  {func} (line {self.function_defs[func][0]})")

        # 6. Analyze complexity (but don't re-analyze after saving)
        if not self.optimized_code_saved:
            self._analyze_complexity(lines)
            print("\n--- COMPLEXITY REPORT ---")
            for func, info in self.function_complexity.items():
                print(f"Function '{func}':")
                print(f"  Time Complexity: {info['time_complexity']}")
                print(f"  Space Complexity: {info['space_complexity']}")
                if info['loops']:
                    print("  Loops:")
                    for loop_line in info['loops']:
                        print(f"    Loop at line {loop_line}")
                if info['recursion']:
                    print("  Recursion detected.")
                if info['components']:
                    print("  Complexity Breakdown:")
                    for comp in info['components']:
                        print(f"    - {comp}")

        # 7. Remove unused code and save optimized code only once
        optimized_code = self._remove_unused_code(code, unused_includes, unused_functions)
        self._save_optimized_code(optimized_code, filename)

        # 8. Generate and save structure tree
        self._generate_structure_tree(lines, filename)

        # Mark that the optimized code has been saved
        self.optimized_code_saved = True

        # Return results, but no further analysis will happen after this
        return {
            "unused_includes": [f"{inc} (line {self.includes[inc]})" for inc in unused_includes],
            "unused_functions": [f"{func} (line {self.function_defs[func][0]})" for func in unused_functions],
            "complexity": self.function_complexity,
            "structure_tree": self.structure_tree,
        }

    def _remove_comments_and_strings(self, code):
        code = re.sub(r'//.*', '', code)
        code = re.sub(r'/\*.*?\*/', '', code, flags=re.DOTALL)
        code = re.sub(r'"(?:\\.|[^"\\])*"', '""', code)
        code = re.sub(r"'(?:\\.|[^'\\])*'", "''", code)
        return code

    def _analyze_includes(self, code):
        for i, line in enumerate(code.split('\n')):
            m = re.match(r'\s*#include\s*[<"]([^>"]+)[>"]', line)
            if m:
                self.includes[m.group(1)] = i+1

    def _analyze_functions_and_calls(self, code, lines):
        func_def_pattern = re.compile(
            r'^[ \t]*(?:[\w:<>]+[ \t*]+)+([a-zA-Z_][a-zA-Z0-9_]*)[ \t]*\(([^)]*)\)[ \t]*(const)?[ \t]*\{', re.MULTILINE)
        for m in func_def_pattern.finditer(code):
            func_name = m.group(1)
            if func_name in self.CONTROL_KEYWORDS:
                continue
            start_line = code[:m.start()].count('\n') + 1
            brace_count = 0
            end_line = start_line
            for idx, line in enumerate(lines[start_line-1:], start=start_line):
                brace_count += line.count('{')
                brace_count -= line.count('}')
                if brace_count == 0:
                    end_line = idx
                    break
            func_code = '\n'.join(lines[start_line-1:end_line])
            self.function_defs[func_name] = (start_line, end_line, func_code)

        call_pattern = re.compile(r'([a-zA-Z_][a-zA-Z0-9_]*)\s*\(')
        for i, line in enumerate(lines):
            for m in call_pattern.finditer(line):
                func_name = m.group(1)
                if func_name in self.CONTROL_KEYWORDS:
                    continue
                for def_func, (start, end, _) in self.function_defs.items():
                    if start <= i+1 <= end:
                        self.function_calls[def_func].add(func_name)
                        break
                if 'main' in self.function_defs and not any(start <= i+1 <= end for start, end, _ in self.function_defs.values()):
                    self.function_calls['main'].add(func_name)

                if func_name in ['printf', 'scanf', 'fopen', 'fclose']:
                    self.used_includes.add('stdio.h')
                elif func_name in ['cout', 'cin']:
                    self.used_includes.add('iostream')
                elif func_name in ['strlen', 'strcpy', 'strcat', 'strcmp']:
                    self.used_includes.add('string.h')
                elif func_name in ['memcpy', 'memset', 'memcmp']:
                    self.used_includes.add('memory.h')

    def _find_used_functions(self):
        used = set()
        queue = deque()
        if 'main' in self.function_defs:
            queue.append('main')
        else:
            return set(self.function_defs)

        while queue:
            func = queue.popleft()
            if func in used:
                continue
            used.add(func)
            for callee in self.function_calls.get(func, []):
                if callee in self.function_defs and callee not in used:
                    queue.append(callee)
        return used

    def _analyze_complexity(self, lines):
        for func, (start, end, func_code) in self.function_defs.items():
            time_complexity = "O(1)"
            space_complexity = "O(1)"  # Default unless something changes
            loop_lines = []
            recursion = False
            max_depth = self._max_loop_depth(func_code)
            components = []

            if max_depth > 0:
                time_complexity = f"O(n^{max_depth})" if max_depth > 1 else "O(n)"
                components.append("loops")
                for idx, line in enumerate(func_code.split('\n'), start=start):
                    if re.search(r'\bfor\b|\bwhile\b', line):
                        loop_lines.append(idx)

            if re.search(rf'\b{func}\s*\(', func_code):
                recursion = True
                components.append("recursion")
                if time_complexity == "O(1)":
                    time_complexity = "O(n)"

            self.function_complexity[func] = {
                'time_complexity': time_complexity,
                'space_complexity': space_complexity,
                'loops': loop_lines,
                'recursion': recursion,
                'components': components
            }

    def _max_loop_depth(self, code):
        tokens = re.findall(r'\b(for|while)\b|[{}]', code)
        max_depth = 0
        current_depth = 0
        stack = []
        for token in tokens:
            if token in ('for', 'while'):
                current_depth += 1
                stack.append('loop')
                max_depth = max(max_depth, current_depth)
            elif token == '{':
                stack.append('{')
            elif token == '}':
                while stack:
                    popped = stack.pop()
                    if popped == 'loop':
                        current_depth -= 1
                        break
        return max_depth

    def _remove_unused_code(self, code, unused_includes, unused_functions):
        lines = code.split('\n')
        for inc in unused_includes:
            for i, line in enumerate(lines):
                if '#include' in line and inc in line:
                    lines[i] = ''
        for func in unused_functions:
            start, end, _ = self.function_defs[func]
            for i in range(start-1, end):
                lines[i] = ''
        return '\n'.join(lines)

    def _save_optimized_code(self, optimized_code, filename):
        optimized_filename = f"optimised_{filename}"
        with open(optimized_filename, 'w') as f:
            f.write(optimized_code)
        print(f"Optimized code saved to '{optimized_filename}'.")

    def _generate_structure_tree(self, lines, filename):
        structure_tree_filename = f"structure_tree_{filename}.txt"
        with open(structure_tree_filename, 'w') as f:
            for func, (start, end, _) in self.function_defs.items():
                f.write(f"Function: {func}, Start: {start}, End: {end}\n")
            for inc, line in self.includes.items():
                f.write(f"Include: {inc}, Line: {line}\n")
        print(f"Code structure saved to '{structure_tree_filename}'.")

import re
import os
from collections import defaultdict, deque

class JavaAnalyzer:
    CONTROL_KEYWORDS = {
        'if', 'for', 'while', 'switch', 'do', 'else', 'case', 'catch',
        'return', 'break', 'continue', 'goto', 'try', 'finally', 'throw'
    }

    def __init__(self):
        self.imports = {}  # import_name -> line_number
        self.used_imports = set()
        self.method_defs = {}  # method_name -> (start_line, end_line, code)
        self.method_calls = defaultdict(set)
        self.method_complexity = {}
        self.structure_tree = []
        self.optimized_code_saved = False

    def analyze_file(self, filename):
        try:
            with open(filename, 'r') as f:
                code = f.read()
        except FileNotFoundError:
            print(f"Error: File '{filename}' not found.")
            return

        cleaned_code = self._remove_comments_and_strings(code)
        lines = code.split('\n')

        # Step 1: Imports
        self._analyze_imports(code)

        # Step 2: Methods and Calls
        self._analyze_methods_and_calls(cleaned_code, lines)

        # Step 3: Used methods via call graph
        used_methods = self._find_used_methods()

        # Step 4: Unused code detection
        unused_imports = set(self.imports) - self.used_imports
        unused_methods = set(self.method_defs) - used_methods

        print("UNUSED IMPORTS:")
        for imp in unused_imports:
            print(f"  {imp} (line {self.imports[imp]})")
        print("\nUNUSED METHODS:")
        for meth in unused_methods:
            print(f"  {meth} (line {self.method_defs[meth][0]})")

        # Step 5: Complexity analysis
        self._analyze_complexity()

        # Step 6: Save structure tree
        self._save_structure_tree(filename)

        # Step 7: Save optimized code
        optimized_code = self._remove_unused_code(code, unused_imports, unused_methods)
        self._save_optimized_code(optimized_code, filename)

        self.optimized_code_saved = True

        return {
            "unused_imports": [f"{imp} (line {self.imports[imp]})" for imp in unused_imports],
            "unused_methods": [f"{meth} (line {self.method_defs[meth][0]})" for meth in unused_methods],
            "complexity": self.method_complexity
        }

    def _remove_comments_and_strings(self, code):
        code = re.sub(r'//.*', '', code)
        code = re.sub(r'/\*.*?\*/', '', code, flags=re.DOTALL)
        code = re.sub(r'"(?:\\.|[^"\\])*"', '""', code)
        code = re.sub(r"'(?:\\.|[^'\\])*'", "''", code)
        return code

    def _analyze_imports(self, code):
        for i, line in enumerate(code.split('\n')):
            m = re.match(r'\s*import\s+([\w\.]+)', line)
            if m:
                self.imports[m.group(1)] = i + 1

    def _analyze_methods_and_calls(self, code, lines):
        method_pattern = re.compile(r'\b([\w<>[\]]+\s+)+([a-zA-Z_][a-zA-Z0-9_]*)\s*\(([^()]*)\)\s*\{')
        i = 0
        while i < len(lines):
            line = lines[i]
            match = method_pattern.search(line)
            if match:
                method_name = match.group(2)
                if method_name in self.CONTROL_KEYWORDS:
                    i += 1
                    continue
                start_line = i + 1
                brace_count = line.count('{') - line.count('}')
                method_lines = [line]
                i += 1
                while i < len(lines) and brace_count > 0:
                    brace_count += lines[i].count('{') - lines[i].count('}')
                    method_lines.append(lines[i])
                    i += 1
                end_line = start_line + len(method_lines) - 1
                method_code = '\n'.join(method_lines)
                self.method_defs[method_name] = (start_line, end_line, method_code)
                self.structure_tree.append(f"Method: {method_name}, Lines: {start_line}-{end_line}")
            else:
                i += 1

        call_pattern = re.compile(r'([a-zA-Z_][a-zA-Z0-9_]*)\s*\(')
        for idx, line in enumerate(lines):
            for m in call_pattern.finditer(line):
                method_name = m.group(1)
                if method_name in self.CONTROL_KEYWORDS:
                    continue
                for def_meth, (start, end, _) in self.method_defs.items():
                    if start <= idx + 1 <= end:
                        self.method_calls[def_meth].add(method_name)
                        break
                for imp in self.imports:
                    if imp.split('.')[-1] == method_name:
                        self.used_imports.add(imp)

    def _find_used_methods(self):
        used = set()
        queue = deque()
        if 'main' in self.method_defs:
            queue.append('main')
        else:
            return set(self.method_defs)
        while queue:
            meth = queue.popleft()
            if meth in used:
                continue
            used.add(meth)
            for callee in self.method_calls.get(meth, []):
                if callee in self.method_defs and callee not in used:
                    queue.append(callee)
        return used

    def _analyze_complexity(self):
        for meth, (start, end, meth_code) in self.method_defs.items():
            loop_lines = []
            recursion = False
            components = []

            max_depth = self._max_loop_depth(meth_code, meth, start, loop_lines)

            time_complexity = "O(1)"
            if max_depth > 0:
                time_complexity = f"O(n^{max_depth})" if max_depth > 1 else "O(n)"
                components.append("loops")

            if re.search(rf'\b{meth}\s*\(', meth_code):
                recursion = True
                components.append("recursion")
                if time_complexity == "O(1)":
                    time_complexity = "O(n)"

            self.method_complexity[meth] = {
                'time_complexity': time_complexity,
                'space_complexity': "O(1)",  # Basic assumption
                'loops': loop_lines,
                'recursion': recursion,
                'components': components
            }

    def _max_loop_depth(self, code, method_name, start_line, loop_lines):
        tokens = re.findall(r'\b(for|while)\b|[{}]', code)
        max_depth = 0
        current_depth = 0
        stack = []
        lines = code.split('\n')
        for idx, line in enumerate(lines):
            if 'for' in line or 'while' in line:
                loop_lines.append(start_line + idx)
        for token in tokens:
            if token in ('for', 'while'):
                current_depth += 1
                stack.append('loop')
                max_depth = max(max_depth, current_depth)
            elif token == '{':
                stack.append('{')
            elif token == '}':
                while stack:
                    popped = stack.pop()
                    if popped == 'loop':
                        current_depth -= 1
                        break
        return max_depth

    def _remove_unused_code(self, code, unused_imports, unused_methods):
        lines = code.split('\n')
        for imp in unused_imports:
            for i, line in enumerate(lines):
                if 'import' in line and imp in line:
                    lines[i] = ''
        for meth in unused_methods:
            start, end, _ = self.method_defs[meth]
            for i in range(start - 1, end):
                lines[i] = ''
        return '\n'.join(lines)

    def _save_optimized_code(self, optimized_code, filename):
        optimized_filename = f"optimized_{filename}"
        with open(optimized_filename, 'w') as f:
            f.write(optimized_code)
        print(f"Optimized code saved to '{optimized_filename}'.")

    def _save_structure_tree(self, filename):
        structure_filename = f"structure_tree_{filename}.txt"
        with open(structure_filename, 'w') as f:
            for entry in self.structure_tree:
                f.write(entry + '\n')
        print(f"Structure tree saved to '{structure_filename}'.")

# Example usage
if __name__ == "__main__":
    analyzer = JavaAnalyzer()
    filename = input("Enter the Java filename to analyze: ")
    results = analyzer.analyze_file(filename)

    print("\n--- Code Analysis Report ---")
    if results:
        if results["unused_imports"]:
            print("\n[Unused Imports]")
            for item in results["unused_imports"]:
                print(f"  {item}")
        if results["unused_methods"]:
            print("\n[Unused Methods]")
            for item in results["unused_methods"]:
                print(f"  {item}")
        print("\n[Complexity]")
        for meth, info in results["complexity"].items():
            print(f"Method '{meth}':")
            print(f"  Time Complexity: {info['time_complexity']}")
            print(f"  Space Complexity: {info['space_complexity']}")
            if info['loops']:
                print("  Loops at lines:", ', '.join(map(str, info['loops'])))
            if info['recursion']:
                print("  Recursion detected.")
            if info['components']:
                print("  Components:", ', '.join(info['components']))

# Main Function and Integration
import os

def analyze_code(filename):
    _, ext = os.path.splitext(filename)
    ext = ext.lower()

    if ext == '.py':
        return analyze_python_code(filename)
    elif ext in ['.c', '.cpp', '.h', '.hpp', '.cc', '.cxx']:
        analyzer = CppAnalyzer()
        return analyzer.analyze_file(filename)
    elif ext == '.java':
        analyzer = JavaAnalyzer()
        return analyzer.analyze_file(filename)
    else:
        return f"Error: Unsupported file type '{ext}'. Supported types: .py, .c, .cpp, .h, .java"

def remove_unused_code(code, unused_imports, unused_functions, language):
    if language == 'python':
        return remove_unused_python_code(code, unused_imports, unused_functions)
    elif language in ['c', 'cpp']:
        return remove_unused_cpp_code(code, unused_imports, unused_functions)
    elif language == 'java':
        return remove_unused_java_code(code, unused_imports, unused_functions)
    else:
        return code

def suggest_secure_coding(code, language):
    if language == 'python':
        return suggest_python_secure_coding(code)
    elif language in ['c', 'cpp']:
        return suggest_cpp_secure_coding(code)
    elif language == 'java':
        return suggest_java_secure_coding(code)
    else:
        return []

def main():
    filename = input("Enter the filename to analyze: ")
    results = analyze_code(filename)

    if isinstance(results, str):
        print(results)
        return

    _, ext = os.path.splitext(filename)
    language = {
        '.py': 'python',
        '.c': 'c',
        '.cpp': 'cpp',
        '.h': 'cpp',
        '.hpp': 'cpp',
        '.cc': 'cpp',
        '.cxx': 'cpp',
        '.java': 'java'
    }.get(ext.lower(), 'unknown')

    print("\n--- Code Analysis Report ---")

    # Unused code report
    print("\n[UNUSED CODE ANALYSIS]")
    if 'unused_imports' in results and results["unused_imports"]:
        print("Unused Imports:", ", ".join(results["unused_imports"]))
    else:
        print("No unused imports found.")

    if 'unused_variables_functions' in results and results["unused_variables_functions"]:
        print("Unused Variables/Functions:", ", ".join(results["unused_variables_functions"]))
    elif 'unused_functions' in results and results["unused_functions"]:
        print("Unused Methods/Functions:", ", ".join(results["unused_functions"]))
    else:
        print("No unused variables or functions found.")

    # Time and Space Complexity Report
    print("\n[TIME AND SPACE COMPLEXITY ANALYSIS]")
    if 'complexity' in results:
        for func, data in results["complexity"].items():
            print(f"\nFunction/Method: {func}")
            print(f"  Time Complexity: {data['time_complexity']}")
            print(f"  Space Complexity: {data['space_complexity']}")

            if data['components']:
                print("\n  Complexity Breakdown:")
                for comp in data['components']:
                    print(f"   - {comp}")
            else:
                print("  No significant complexity contributors found within loops or calls.")



    # Remove unused code and save
    if 'unused_imports' in results and ('unused_variables_functions' in results or 'unused_functions' in results):
        unused_funcs = results.get('unused_variables_functions', results.get('unused_functions', []))
        optimized_code = remove_unused_code(
            results["original_code"],
            results["unused_imports"],
            unused_funcs,
            language
        )

        base, ext = os.path.splitext(filename)
        optimized_filename = f"optimized_{base}{ext}"

        with open(optimized_filename, 'w') as f:
            f.write(optimized_code)
        print(f"\nOptimized code (unused parts removed) saved to '{optimized_filename}'")


if __name__ == "__main__":
    main()